/** Generated by scripts/generate-types.ts. Do not edit. */
export type JsonValue =
  | null
  | boolean
  | number
  | string
  | JsonValue[]
  | { [key: string]: JsonValue };

export type ArtifactsBrief = {
  requirements: Array<{
    id: string;
    trace_id?: string;
    description: string;
    priority: "must" | "should" | "could";
    rationale?: string;
  }>;
  constraints: Array<{ type: "hard" | "soft"; description: string; source: string }>;
  non_goals: Array<{ description: string; reason: string }>;
  style: { tone: string; patterns?: Array<string>; conventions?: Array<string> };
  key_concepts: Array<{ term: string; definition: string }>;
  decisions: Array<{
    decision: string;
    rationale: string;
    alternatives_considered?: Array<string>;
  }>;
  open_questions: Array<string>;
  context_manifest?: {
    selection_policy: string;
    ordering_policy: string;
    files_loaded: Array<{ path: string; bytes: number }>;
    docs_loaded: Array<{ url: string; retrieved_at: string }>;
    token_estimate?: number;
    char_count_estimate?: number;
  };
};

export type ArtifactsBuildReport = {
  trace_id?: string;
  summary: string;
  outputs: Array<string>;
  covers_requirement_ids?: Array<string>;
  groups?: Array<{
    group_id: string;
    status: "pass" | "fail" | "skip";
    tasks_completed?: number;
    tasks_total?: number;
    errors?: Array<string>;
  }>;
  context_manifest?: {
    selection_policy: string;
    ordering_policy: string;
    files_loaded: Array<{ path: string; bytes: number }>;
    docs_loaded: Array<{ url: string; retrieved_at: string }>;
    token_estimate?: number;
    char_count_estimate?: number;
  };
};

export type ArtifactsContextManifestGate = {
  context_manifest: {
    selection_policy: string;
    ordering_policy: string;
    files_loaded: Array<{ path: string; bytes: number }>;
    docs_loaded: Array<{ url: string; retrieved_at: string }>;
    token_estimate: number;
    char_count_estimate?: number;
  };
};

export type ArtifactsDesignDocument = {
  analysis: { summary: string; principles: Array<{ principle: string; implication: string }> };
  constraints_classification: Array<{
    constraint: string;
    trace_id?: string;
    covers_requirement_ids?: Array<string>;
    original_type: "hard" | "soft";
    validated_type: "hard" | "soft";
    evaluation: string;
    flagged?: boolean;
  }>;
  approach: {
    description: string;
    rationale: string;
    components?: Array<{ name: string; responsibility: string; interfaces?: Array<string> }>;
  };
  research: Array<{ source: string; url?: string; finding: string; verified_at: string }>;
  codebase_alignment: Array<{
    pattern: string;
    file_paths?: Array<string>;
    alignment_status: "aligned" | "divergent" | "new";
    notes?: string;
  }>;
  iteration_history: Array<{ iteration: number; changes: string; rationale: string }>;
  context_manifest?: {
    selection_policy: string;
    ordering_policy: string;
    files_loaded: Array<{ path: string; bytes: number }>;
    docs_loaded: Array<{ url: string; retrieved_at: string }>;
    token_estimate?: number;
    char_count_estimate?: number;
  };
};

export type ArtifactsDriftReport = {
  source_document: { type: "design" | "plan"; ref: string };
  target_document: { type: "plan" | "implementation"; ref: string };
  claims: Array<{
    id: string;
    trace_id?: string;
    claim: string;
    claim_type: "interface" | "invariant" | "security" | "performance" | "docs";
    covers_requirement_ids?: Array<string>;
    verification_status: "verified" | "violated" | "partial" | "unverifiable";
    evidence: string;
    extractor: string;
    drift_score?: number;
    confidence?: number;
  }>;
  analysis_complete?: boolean;
  findings: Array<{
    description: string;
    claim_type?: "interface" | "invariant" | "security" | "performance" | "docs";
    severity: "critical" | "high" | "medium" | "low";
    claim_ids: Array<string>;
    mitigation?: string;
  }>;
  adjudication: {
    mode: "heuristic" | "dual-extractor";
    extractors: Array<string>;
    conflicts_resolved: number;
    resolution_policy: string;
  };
  context_manifest?: {
    selection_policy: string;
    ordering_policy: string;
    files_loaded: Array<{ path: string; bytes: number }>;
    docs_loaded: Array<{ url: string; retrieved_at: string }>;
    token_estimate?: number;
    char_count_estimate?: number;
  };
};

export type ArtifactsExecutionPlanDefsExecutionSession = {
  session_id: string;
  session_kind: "build-task" | "quality-case";
  fresh_context: true;
  inherits_history: false;
  max_attempts: number;
  retry_behavior: "restart-fresh-session" | "manual-escalation";
};

export type ArtifactsExecutionPlanDefsTaskContextManifest = {
  selection_policy: string;
  ordering_policy: string;
  files_loaded: Array<{ path: string; bytes: number }>;
  docs_loaded: Array<{ url: string; retrieved_at: string }>;
  token_estimate?: number;
  char_count_estimate?: number;
};

export type ArtifactsExecutionPlanDefsCommandContract = {
  command: string;
  working_directory?: string;
  success_signal?: string;
};

export type ArtifactsExecutionPlanDefsEvidenceRequirement = {
  type: string;
  why: string;
  required?: boolean;
};

export type ArtifactsExecutionPlan = {
  task_groups: Array<{
    group_id: string;
    builder_tier?: "high_reasoning" | "balanced" | "fast";
    scope_override?: { reason: string };
    tasks: Array<{
      id: string;
      trace_id?: string;
      description: string;
      execution_session: ArtifactsExecutionPlanDefsExecutionSession;
      context_manifest: ArtifactsExecutionPlanDefsTaskContextManifest;
      covers_requirement_ids?: Array<string>;
      covers_constraint_ids?: Array<string>;
      file_paths: Array<string>;
      code_patterns: Array<{ file: string; pattern: string; description?: string }>;
      test_cases: Array<{
        name: string;
        trace_id?: string;
        execution_session: ArtifactsExecutionPlanDefsExecutionSession;
        context_manifest: ArtifactsExecutionPlanDefsTaskContextManifest;
        covers_requirement_ids?: Array<string>;
        setup: string;
        assertion: string;
        expected: string;
      }>;
      acceptance_criteria: Array<string>;
      dependencies?: Array<string>;
      allowed_paths?: Array<string>;
      out_of_scope_paths?: Array<string>;
      verify?: ArtifactsExecutionPlanDefsCommandContract;
      guard?: { rule: string; command?: string; metric?: string };
      required_evidence?: Array<ArtifactsExecutionPlanDefsEvidenceRequirement>;
    }>;
  }>;
  file_ownership: { [key: string]: unknown };
  documentation?: JsonValue & { required: boolean; paths: Array<string>; rationale: string };
  verification_commands: Array<{
    command: string;
    description: string;
    working_directory: string;
    evidence_roles: Array<"build" | "quality-static" | "quality-tests" | "post-build">;
    evidence_kind: "build" | "static" | "tests" | "security";
  }>;
  context_manifest?: {
    selection_policy: string;
    ordering_policy: string;
    files_loaded: Array<{ path: string; bytes: number }>;
    docs_loaded: Array<{ url: string; retrieved_at: string }>;
    token_estimate?: number;
    char_count_estimate?: number;
  };
};

export type ArtifactsExecutionTrace = {
  ts: string;
  run_id: string;
  seq?: number;
  event_id?: string;
  parent_event_id?: string;
  input_digests?: Array<string>;
  output_digests?: Array<string>;
  event:
    | string
    | (
        | "run_start"
        | "phase_start"
        | "phase_end"
        | "task_session_start"
        | "task_session_end"
        | "review_state_change"
        | "artifact_read"
        | "artifact_write"
        | "agent_call"
        | "gate_result"
        | "retry"
        | "error"
        | "run_end"
        | "checkpoint_requested"
        | "checkpoint_resolved"
        | "run_waiting"
        | "run_resumed"
        | "run_stop_requested"
        | "run_stopped"
        | "run_interrupted"
        | "run_blocked"
        | "run_completed"
      );
  phase: string;
  status?:
    | "pass"
    | "fail"
    | "warn"
    | "ok"
    | "error"
    | "retry"
    | "waiting"
    | "stopped"
    | "interrupted"
    | "blocked"
    | "completed";
  artifact_ref?: string;
  gate_id?: string;
  tool_name?: string;
  tier?: "high_reasoning" | "balanced" | "fast";
  model_hint?: string;
  activity_id?: string;
  runtime_name?: string;
  runtime_version?: string;
  tokens_in?: number;
  tokens_out?: number;
  cost_usd?: number;
  duration_ms?: number;
  error_code?: string;
  message?: string;
  metadata?: { [key: string]: unknown };
};

export type ArtifactsOperatorCheckpoint = JsonValue & {
  schema_version: "1.0.0";
  checkpoint_id: string;
  request_key: string;
  run_id: string;
  phase: string;
  purpose: "mutation" | "ship";
  status: "pending" | "approved" | "rejected" | "escalated";
  message: string;
  requested_by: string;
  requested_at: string;
  decision?: {
    decision_id: string;
    outcome: "approved" | "rejected" | "escalated";
    actor: string;
    at: string;
    rationale: string;
  };
  resolved_at?: string;
};

export type ArtifactsOperatorControl = {
  schema_version: "1.0.0";
  run_id: string;
  status:
    | "running"
    | "waiting"
    | "stop-requested"
    | "stopped"
    | "interrupted"
    | "blocked"
    | "completed";
  stop_requested: boolean;
  stop_requested_at?: string;
  interrupted_at?: string;
  waiting_checkpoint_id?: string | null;
  updated_at: string | null;
};

export type ArtifactsProgressSummary = {
  run_id: string;
  current_phase: string;
  workspace_mode: string;
  phase_status: Array<{
    phase: string;
    status: "pending" | "active" | "completed" | "blocked";
    gate_status: "pass" | "warn" | "fail" | "pending";
  }>;
  gate_totals: { pass: number; warn: number; fail: number; pending: number };
  blockers: Array<string>;
  activity_summary?: Array<{
    activity_id: string;
    count: number;
    tier?: string;
    model_hint?: string;
    runtime_name?: string;
    runtime_version?: string;
  }>;
  cost_summary?: { total_cost_usd: number; total_tokens_in: number; total_tokens_out: number };
  workspace?: {
    root?: string;
    primary_repo_root?: string;
    branch?: string;
    worktree_path?: string;
    cleanup_command?: string;
  };
  reaction_events?: Array<{
    event: string;
    status: string;
    source?: string;
    note?: string;
    recorded_at?: string;
  }>;
  next_action: string;
  updated_at: string;
};

export type ArtifactsQualityReport = (JsonValue & JsonValue) & {
  audit_type: "static" | "tests" | "denoise" | "frontend" | "backend" | "docs" | "security";
  violations: Array<
    JsonValue & {
      rule: string;
      trace_id?: string;
      covers_requirement_ids?: Array<string>;
      severity: "critical" | "high" | "medium" | "low" | "info";
      file: string;
      line?: number;
      evidence: string;
      remediation: string;
      status: "open" | "fixed" | "accepted-risk";
      category?:
        | "access-control"
        | "xss"
        | "csrf"
        | "secrets"
        | "security-headers"
        | "cookies-session"
        | "production-exposure"
        | "dependencies"
        | "ssrf"
        | "file-upload"
        | "injection"
        | "path-traversal"
        | "open-redirect"
        | "jwt-auth";
      cwe?: string;
      owasp?: string;
      owner?: string;
      expiry?: string;
      fix_ref?: string;
    }
  >;
  summary: {
    pass: number;
    warn: number;
    fail: number;
    open: number;
    fixed: number;
    accepted_risk: number;
  };
  security_audit?: JsonValue & {
    categories_covered: Array<
      | "access-control"
      | "xss"
      | "csrf"
      | "secrets"
      | "security-headers"
      | "cookies-session"
      | "production-exposure"
      | "dependencies"
      | "ssrf"
      | "file-upload"
      | "injection"
      | "path-traversal"
      | "open-redirect"
      | "jwt-auth"
    >;
    checks: {
      access_control: true;
      xss: true;
      csrf: true;
      secrets: true;
      security_headers: true;
      cookies_session: true;
      production_exposure: true;
      dependencies: true;
      ssrf: true;
      file_upload: true;
      injection: true;
      path_traversal: true;
      open_redirect: true;
      jwt_auth: true;
    };
    fix_loop: {
      rounds: number;
      critical_high_before: number;
      critical_high_after: 0;
      rescan_completed: true;
    };
    tools: Array<string>;
    risk_signoff_required: boolean;
    risk_signoffs?: Array<{
      owner: string;
      justification: string;
      expiry: string;
      follow_up: string;
    }>;
  };
  coverage_ledger?: {
    coverage_scope: "must-requirements";
    requirements: Array<{
      requirement_id: string;
      planned_task_ids: Array<string>;
      planned_test_cases: Array<string>;
      acceptance_criteria: Array<string>;
      missing_task_ids: Array<string>;
      missing_test_cases: Array<string>;
      status: "covered" | "partial" | "missing";
    }>;
    summary: {
      total_requirements: number;
      covered_requirements: number;
      partial_requirements: number;
      missing_requirements: number;
    };
  };
  qc_summary?: {
    headline: string;
    coverage_status: "complete" | "partial" | "missing";
    covered_requirements: Array<string>;
    missing_requirement_ids: Array<string>;
  };
  evidence_bundle?: {
    status: "complete" | "partial" | "missing";
    references: Array<{ type: string; path: string; description?: string; user_surface?: boolean }>;
    missing_types: Array<string>;
    residual_gaps: Array<string>;
  };
  residual_gaps?: Array<string>;
  context_manifest?: {
    selection_policy: string;
    ordering_policy: string;
    files_loaded: Array<{ path: string; bytes: number }>;
    docs_loaded: Array<{ url: string; retrieved_at: string }>;
    token_estimate?: number;
    char_count_estimate?: number;
  };
};

export type ArtifactsReleaseReadiness = (JsonValue & JsonValue & JsonValue) & {
  release_decision: "go" | "no-go" | "conditional";
  semver_impact: "patch" | "minor" | "major" | "none";
  changelog: { updated: boolean; path: string; entries: Array<string> };
  migration: { required: boolean; doc_path?: string; validated: boolean };
  rollback: { strategy: string; owner: string; tested: boolean };
  open_risks: Array<{ risk: string; owner: string; due_date: string; mitigation_plan?: string }>;
  approvals: Array<{ owner: string; approved_at: string; notes?: string }>;
  review_loop_ref: string;
  review_state: {
    explain_status:
      | "not-started"
      | "in-progress"
      | "pending-approval"
      | "approved"
      | "rejected"
      | "completed";
    fix_status:
      | "not-started"
      | "in-progress"
      | "pending-approval"
      | "approved"
      | "rejected"
      | "completed";
    ship_status:
      | "not-started"
      | "in-progress"
      | "pending-approval"
      | "approved"
      | "rejected"
      | "completed";
  };
  conditions?: Array<string>;
  evidence_bundle?: {
    status: "complete" | "partial" | "missing";
    references: Array<{ type: string; path: string; description?: string; user_surface?: boolean }>;
    missing_types: Array<string>;
    residual_gaps: Array<string>;
  };
  residual_gaps?: Array<string>;
  context_manifest?: {
    selection_policy: string;
    ordering_policy: string;
    files_loaded: Array<{ path: string; bytes: number }>;
    docs_loaded: Array<{ url: string; retrieved_at: string }>;
    token_estimate?: number;
    char_count_estimate?: number;
  };
};

export type ArtifactsReviewLoopDefsReviewState = {
  status:
    | "not-started"
    | "in-progress"
    | "pending-approval"
    | "approved"
    | "rejected"
    | "completed";
  code_mutation_allowed: boolean;
  approval_required: boolean;
  note?: string;
};

export type ArtifactsReviewLoop = {
  run_id: string;
  current_state: "explain" | "fix" | "ship";
  states: {
    explain: ArtifactsReviewLoopDefsReviewState;
    fix: ArtifactsReviewLoopDefsReviewState;
    ship: ArtifactsReviewLoopDefsReviewState;
  };
  transition_log: Array<{
    state: "explain" | "fix" | "ship";
    status:
      | "not-started"
      | "in-progress"
      | "pending-approval"
      | "approved"
      | "rejected"
      | "completed";
    changed_at: string;
    note?: string;
  }>;
  updated_at: string;
};

export type ArtifactsReviewReport = {
  reviewers: Array<{
    model_id: string;
    findings: Array<{
      id: string;
      trace_id?: string;
      category: string;
      description: string;
      severity: "critical" | "high" | "medium" | "low" | "info";
      covers_requirement_ids?: Array<string>;
      evidence?: string;
      suggestion?: string;
    }>;
  }>;
  deduplicated_findings: Array<{
    id: string;
    trace_id?: string;
    category: string;
    description: string;
    severity: "critical" | "high" | "medium" | "low" | "info";
    source_models: Array<string>;
    covers_requirement_ids?: Array<string>;
    evidence?: string;
    suggestion?: string;
  }>;
  fact_checks: Array<{
    finding_id: string;
    status: "confirmed" | "refuted" | "inconclusive";
    evidence: string;
  }>;
  cost_benefit: Array<{
    finding_id: string;
    severity: "critical" | "high" | "medium" | "low" | "info";
    fix_cost: "trivial" | "low" | "medium" | "high" | "prohibitive";
    risk_of_ignoring: "catastrophic" | "high" | "moderate" | "low" | "negligible";
    recommendation: "fix-now" | "fix-before-ship" | "defer" | "accept" | "wont-fix";
  }>;
  mitigations: Array<{
    finding_id: string;
    status: "mitigated" | "deferred" | "accepted";
    action?: string;
    justification?: string;
  }>;
  iteration: { loop_count: number; remaining_unmitigated: Array<string> };
  context_manifest?: {
    selection_policy: string;
    ordering_policy: string;
    files_loaded: Array<{ path: string; bytes: number }>;
    docs_loaded: Array<{ url: string; retrieved_at: string }>;
    token_estimate?: number;
    char_count_estimate?: number;
  };
};

export type ArtifactsTraceabilityCheck = {
  must_requirement_ids: Array<string>;
  plan_task_requirement_ids: Array<string>;
  plan_test_requirement_ids: Array<string>;
  drift_requirement_ids: Array<string>;
  design_requirement_ids: Array<string>;
  sources?: { brief_ref?: string; plan_ref?: string; drift_ref?: string; design_ref?: string };
};

export type AutonomousPolicyDefsDesignInputs = Array<"brief.json">;

export type AutonomousPolicyDefsAdversarialReviewInputs = Array<"brief.json" | "design.json">;

export type AutonomousPolicyDefsPlanInputs = Array<"brief.json" | "design.json" | "review.json">;

export type AutonomousPolicyDefsPmatchInputs = (JsonValue & JsonValue) &
  Array<"brief.json" | "design.json" | "plan.json">;

export type AutonomousPolicyDefsBuildInputs = (JsonValue & JsonValue) &
  Array<"brief.json" | "design.json" | "plan.json" | "drift-reports/pmatch.json">;

export type AutonomousPolicyDefsQualityStaticInputs = (JsonValue & JsonValue) &
  Array<"brief.json" | "plan.json" | "build.json">;

export type AutonomousPolicyDefsQualityTestsInputs = (JsonValue & JsonValue) &
  Array<"brief.json" | "plan.json" | "build.json" | "quality-reports/static.json">;

export type AutonomousPolicyDefsPostBuildInputs = (JsonValue & JsonValue & JsonValue & JsonValue) &
  Array<
    | "brief.json"
    | "design.json"
    | "plan.json"
    | "build.json"
    | "quality-reports/static.json"
    | "quality-reports/tests.json"
  >;

export type AutonomousPolicyDefsReleaseReadinessInputs = (JsonValue &
  JsonValue &
  JsonValue &
  JsonValue &
  JsonValue &
  JsonValue &
  JsonValue) &
  Array<
    | "brief.json"
    | "design.json"
    | "review.json"
    | "plan.json"
    | "drift-reports/pmatch.json"
    | "build.json"
    | "quality-reports/static.json"
    | "quality-reports/tests.json"
    | "quality-reports/post-build.json"
  >;

export type AutonomousPolicy = {
  schema_version: "1.0.0";
  policy_id: string;
  phase_guidance: {
    arm: string;
    design: string;
    "adversarial-review": string;
    plan: string;
    pmatch: string;
    build: string;
    "quality-static": string;
    "quality-tests": string;
    "post-build": string;
    "release-readiness": string;
  };
  phase_inputs: {
    arm: Array<JsonValue>;
    design: AutonomousPolicyDefsDesignInputs;
    "adversarial-review": AutonomousPolicyDefsAdversarialReviewInputs;
    plan: AutonomousPolicyDefsPlanInputs;
    pmatch: AutonomousPolicyDefsPmatchInputs;
    build: AutonomousPolicyDefsBuildInputs;
    "quality-static": AutonomousPolicyDefsQualityStaticInputs;
    "quality-tests": AutonomousPolicyDefsQualityTestsInputs;
    "post-build": AutonomousPolicyDefsPostBuildInputs;
    "release-readiness": AutonomousPolicyDefsReleaseReadinessInputs;
  };
};

export type ExperimentsEvidenceManifestV1 = {
  schema_version: "1.0.0";
  experiment_id: string;
  experiment_digest: string;
  suite_digest: string;
  input_digest: string;
  trial_id: string;
  arm_id: string;
  task_id: string;
  repetition: number;
  sequence: number;
  run_id: string;
  created_at: string;
  files: Array<{ path: string; sha256: string; bytes: number; executable: boolean }>;
};

export type ExperimentsExperimentReportV1DefsDigest = string;

export type ExperimentsExperimentReportV1DefsMetricName =
  | "pass_rate"
  | "ship_rate"
  | "acceptance_rate"
  | "wall_clock_ms"
  | "provider_attempts"
  | "repair_rounds"
  | "total_tokens"
  | "output_tokens"
  | "estimated_cost"
  | "seeded_defects_shipped"
  | "changed_paths";

export type ExperimentsExperimentReportV1DefsProportion = {
  successes: number;
  trials: number;
  estimate: number | null;
  ci_low: number | null;
  ci_high: number | null;
  method: "wilson";
};

export type ExperimentsExperimentReportV1DefsArmSummary = {
  arm_id: string;
  label: string;
  n: number;
  proportions: {
    pass_rate: ExperimentsExperimentReportV1DefsProportion;
    ship_rate: ExperimentsExperimentReportV1DefsProportion;
    acceptance_rate: ExperimentsExperimentReportV1DefsProportion;
  };
  metrics: { [key: string]: unknown };
  pass_at_k: Array<{ k: number; estimate: number | null; tasks: number }>;
  tokens_measurement: { complete: number; partial: number; unavailable: number };
};

export type ExperimentsExperimentReportV1DefsInterval = {
  estimate: number | null;
  ci_low: number | null;
  ci_high: number | null;
  method: "wilson" | "bootstrap-percentile" | "exact";
};

export type ExperimentsExperimentReportV1DefsComparison = {
  arm: string;
  control: string;
  metric: ExperimentsExperimentReportV1DefsMetricName;
  paired: boolean;
  n: number;
  difference: ExperimentsExperimentReportV1DefsInterval;
  test: "mcnemar-exact" | "paired-permutation" | "unpaired-permutation" | "none";
  p_value: number | null;
  p_value_adjusted: number | null;
  effect_size: { name: "risk-difference" | "cliffs-delta"; value: number | null };
  discordant?: { arm_only: number; control_only: number };
  significant: boolean;
};

export type ExperimentsExperimentReportV1 = {
  schema_version: "1.0.0";
  experiment_id: string;
  experiment_digest: ExperimentsExperimentReportV1DefsDigest;
  suite_digest: ExperimentsExperimentReportV1DefsDigest;
  generated_at: string;
  analysis: {
    alpha: number;
    bootstrap_samples: number;
    permutation_samples: number;
    correction: "none" | "holm";
    seed: number;
    paired: boolean;
    primary_metric: ExperimentsExperimentReportV1DefsMetricName;
    minimum_detectable_effect?: number;
  };
  trials: {
    planned: number;
    completed: number;
    launch_failed: number;
    collect_failed: number;
    skipped: number;
    missing: number;
  };
  arms: Array<ExperimentsExperimentReportV1DefsArmSummary>;
  comparisons: Array<ExperimentsExperimentReportV1DefsComparison>;
  agreement?: {
    raters: Array<string>;
    n: number;
    cohens_kappa: number | null;
    observed_agreement: number | null;
  } | null;
  verdict: {
    status: "supported" | "refuted" | "inconclusive" | "not-evaluated";
    primary_metric: ExperimentsExperimentReportV1DefsMetricName;
    treatment_arm: string;
    control_arm: string;
    expected: "treatment-greater" | "treatment-less";
    rationale: string;
  };
  card: {
    title: string;
    suite: {
      suite_id: string;
      revision: number;
      task_count: number;
      contamination_note: string;
      license: string;
    };
    hypothesis: { [key: string]: unknown };
    arms: Array<{ arm_id: string; label: string; run: { [key: string]: unknown } }>;
    provenance: {
      workflow_digests: Array<string>;
      policy_digests: Array<string>;
      execution_profile_digests: Array<string>;
      providers: Array<string>;
      models: Array<string>;
      runtime_identities: Array<{ [key: string]: unknown }>;
    };
    limitations: Array<string>;
    reproduction: { commands: Array<string> };
  };
};

export type ExperimentsExperimentReportV2DefsDigest = string;

export type ExperimentsExperimentReportV2DefsMetricName =
  | "pass_rate"
  | "ship_rate"
  | "acceptance_rate"
  | "wall_clock_ms"
  | "provider_attempts"
  | "repair_rounds"
  | "total_tokens"
  | "output_tokens"
  | "estimated_cost"
  | "seeded_defects_shipped"
  | "changed_paths";

export type ExperimentsExperimentReportV2DefsProportion = {
  successes: number;
  trials: number;
  estimate: number | null;
  ci_low: number | null;
  ci_high: number | null;
  method: "wilson" | "task-bootstrap-percentile";
  units: number;
};

export type ExperimentsExperimentReportV2DefsArmSummary = {
  arm_id: string;
  label: string;
  n: number;
  proportions: {
    pass_rate: ExperimentsExperimentReportV2DefsProportion;
    ship_rate: ExperimentsExperimentReportV2DefsProportion;
    acceptance_rate: ExperimentsExperimentReportV2DefsProportion;
  };
  metrics: { [key: string]: unknown };
  pass_at_k: Array<{ k: number; estimate: number | null; tasks: number }>;
  tokens_measurement: { complete: number; partial: number; unavailable: number };
  coverage: {
    planned: number;
    completed: number;
    launch_failed: number;
    collect_failed: number;
    skipped: number;
    missing: number;
    pass_observed: number;
    pass_unknown: number;
    pass_rate_lower: number | null;
    pass_rate_upper: number | null;
  };
};

export type ExperimentsExperimentReportV2DefsInterval = {
  estimate: number | null;
  ci_low: number | null;
  ci_high: number | null;
  method: "wilson" | "bootstrap-percentile" | "exact";
};

export type ExperimentsExperimentReportV2DefsComparison = {
  arm: string;
  control: string;
  metric: ExperimentsExperimentReportV2DefsMetricName;
  paired: boolean;
  n: number;
  difference: ExperimentsExperimentReportV2DefsInterval;
  test: "mcnemar-exact" | "paired-permutation" | "unpaired-permutation" | "none";
  p_value: number | null;
  p_value_adjusted: number | null;
  effect_size: { name: "risk-difference" | "cliffs-delta"; value: number | null };
  discordant?: { arm_only: number; control_only: number };
  significant: boolean;
  arm_observed: number;
  control_observed: number;
  matched_trials: number;
  unit: "task" | "trial";
};

export type ExperimentsExperimentReportV2 = {
  schema_version: "2.0.0";
  experiment_id: string;
  experiment_digest: ExperimentsExperimentReportV2DefsDigest;
  suite_digest: ExperimentsExperimentReportV2DefsDigest;
  generated_at: string;
  analysis: {
    alpha: number;
    bootstrap_samples: number;
    permutation_samples: number;
    correction: "none" | "holm";
    seed: number;
    paired: boolean;
    primary_metric: ExperimentsExperimentReportV2DefsMetricName;
    minimum_detectable_effect?: number;
    unit: "task" | "trial";
    multiplicity_family: "all-arm-metric-comparisons";
    implementation: string;
  };
  trials: {
    planned: number;
    completed: number;
    launch_failed: number;
    collect_failed: number;
    skipped: number;
    missing: number;
  };
  arms: Array<ExperimentsExperimentReportV2DefsArmSummary>;
  comparisons: Array<ExperimentsExperimentReportV2DefsComparison>;
  agreement?: {
    raters: Array<string>;
    n: number;
    cohens_kappa: number | null;
    observed_agreement: number | null;
  } | null;
  verdict: {
    status: "supported" | "refuted" | "inconclusive" | "not-evaluated";
    primary_metric: ExperimentsExperimentReportV2DefsMetricName;
    treatment_arm: string;
    control_arm: string;
    expected: "treatment-greater" | "treatment-less";
    rationale: string;
  };
  card: {
    title: string;
    suite: {
      suite_id: string;
      revision: number;
      task_count: number;
      contamination_note: string;
      license: string;
    };
    hypothesis: { [key: string]: unknown };
    arms: Array<{ arm_id: string; label: string; run: { [key: string]: unknown } }>;
    provenance: {
      workflow_digests: Array<string>;
      policy_digests: Array<string>;
      execution_profile_digests: Array<string>;
      providers: Array<string>;
      models: Array<string>;
      runtime_identities: Array<{ [key: string]: unknown }>;
    };
    limitations: Array<string>;
    reproduction: { commands: Array<string> };
  };
  task_results: Array<{
    arm_id: string;
    task_id: string;
    metric: ExperimentsExperimentReportV2DefsMetricName;
    planned: number;
    observed: number;
    mean: number | null;
  }>;
  records_digest: ExperimentsExperimentReportV2DefsDigest;
  input_digest: string | null;
};

export type ExperimentsExperimentV1DefsArmId = string;

export type ExperimentsExperimentV1DefsRelativePath = string;

export type ExperimentsExperimentV1DefsIdentifier = string;

export type ExperimentsExperimentV1DefsArm = {
  arm_id: ExperimentsExperimentV1DefsArmId;
  label: string;
  description?: string;
  run: {
    workflow?: ExperimentsExperimentV1DefsRelativePath;
    execution_profile?: ExperimentsExperimentV1DefsRelativePath;
    policy?: ExperimentsExperimentV1DefsRelativePath;
    context_mode?: "legacy" | "bounded";
    provider?: "auto" | "codex" | "opencode" | "command";
    model?: string;
    reasoning_effort?: "low" | "medium" | "high" | "xhigh";
    variant?: string;
    graph_memory?: "off" | "read" | "read-write";
    max_concurrency?: number;
    max_repair_rounds?: number;
    timeout_seconds?: number;
    agent_command?: string;
    agent_args?: Array<string>;
    allow_unsafe_command_provider?: boolean;
  };
  pricing?: {
    currency: string;
    input_per_million: number;
    cached_input_per_million?: number;
    output_per_million: number;
    reasoning_output_per_million?: number;
  };
};

export type ExperimentsExperimentV1DefsMetricName =
  | "pass_rate"
  | "ship_rate"
  | "acceptance_rate"
  | "wall_clock_ms"
  | "provider_attempts"
  | "repair_rounds"
  | "total_tokens"
  | "output_tokens"
  | "estimated_cost"
  | "seeded_defects_shipped"
  | "changed_paths";

export type ExperimentsExperimentV1 = {
  schema_version: "1.0.0";
  experiment_id: string;
  revision: number;
  title: string;
  description?: string;
  hypothesis: {
    claim_id?: string;
    statement: string;
    treatment_arm: ExperimentsExperimentV1DefsArmId;
    control_arm: ExperimentsExperimentV1DefsArmId;
    expected: "treatment-greater" | "treatment-less";
    falsifier: string;
  };
  suite: {
    path: ExperimentsExperimentV1DefsRelativePath;
    digest?: string;
    task_ids?: Array<ExperimentsExperimentV1DefsIdentifier>;
    tags?: Array<string>;
  };
  arms: Array<ExperimentsExperimentV1DefsArm>;
  design: {
    repetitions: number;
    seed: number;
    order?: "interleaved" | "sequential";
    paired?: boolean;
    max_trial_wall_clock_seconds?: number;
  };
  metrics: {
    primary: ExperimentsExperimentV1DefsMetricName;
    secondary?: Array<ExperimentsExperimentV1DefsMetricName>;
    pass_at_k?: Array<number>;
  };
  analysis: {
    unit?: "task" | "trial";
    alpha: number;
    bootstrap_samples?: number;
    permutation_samples?: number;
    correction?: "none" | "holm";
    minimum_detectable_effect?: number;
  };
  budgets?: { max_trials?: number; max_wall_clock_seconds?: number; max_estimated_cost?: number };
};

export type ExperimentsTaskSuiteV1DefsIdentifier = string;

export type ExperimentsTaskSuiteV1DefsArgv = Array<string>;

export type ExperimentsTaskSuiteV1DefsRelativePath = string;

export type ExperimentsTaskSuiteV1DefsCheck =
  | {
      check_id: ExperimentsTaskSuiteV1DefsIdentifier;
      kind: "command";
      command: ExperimentsTaskSuiteV1DefsArgv;
      expected_exit_code?: number;
      timeout_seconds?: number;
      description?: string;
    }
  | {
      check_id: ExperimentsTaskSuiteV1DefsIdentifier;
      kind: "path-exists" | "path-absent";
      path: ExperimentsTaskSuiteV1DefsRelativePath;
      description?: string;
    }
  | {
      check_id: ExperimentsTaskSuiteV1DefsIdentifier;
      kind: "file-contains" | "file-lacks";
      path: ExperimentsTaskSuiteV1DefsRelativePath;
      pattern: string;
      description?: string;
    };

export type ExperimentsTaskSuiteV1DefsSeededDefect = {
  defect_id: ExperimentsTaskSuiteV1DefsIdentifier;
  description: string;
  detector: ExperimentsTaskSuiteV1DefsCheck;
};

export type ExperimentsTaskSuiteV1DefsTask = {
  task_id: ExperimentsTaskSuiteV1DefsIdentifier;
  title: string;
  prompt: string;
  repository: ExperimentsTaskSuiteV1DefsIdentifier;
  tags?: Array<string>;
  difficulty?: "trivial" | "easy" | "medium" | "hard";
  acceptance: { checks: Array<ExperimentsTaskSuiteV1DefsCheck>; require_all?: boolean };
  seeded_defects?: Array<ExperimentsTaskSuiteV1DefsSeededDefect>;
  reference_note?: string;
};

export type ExperimentsTaskSuiteV1 = {
  schema_version: "1.0.0";
  suite_id: string;
  revision: number;
  title: string;
  description?: string;
  provenance: {
    created?: string;
    authors: Array<string>;
    license: string;
    sources?: Array<string>;
    contamination_note: string;
  };
  repositories: { [key: string]: unknown };
  tasks: Array<ExperimentsTaskSuiteV1DefsTask>;
};

export type ExperimentsTrialExecutionV1 = {
  schema_version: "1.0.0";
  experiment_id: string;
  experiment_digest: string;
  suite_digest: string;
  input_digest: string;
  trial_id: string;
  arm_id: string;
  task_id: string;
  repetition: number;
  sequence: number;
  phase: "started" | "finished" | "acknowledged";
  started_at: string;
  finished_at?: string;
  elapsed_ms?: number | null;
  record_digest?: string;
  recovered?: boolean;
  runner: { pid: number; hostname: string };
  acknowledged_at?: string;
  requires_acknowledgment?: boolean;
};

export type ExperimentsTrialRecordV1DefsDigest = string;

export type ExperimentsTrialRecordV1DefsTimestamp = string;

export type ExperimentsTrialRecordV1DefsCheckResult = {
  check_id: string;
  kind: "command" | "path-exists" | "path-absent" | "file-contains" | "file-lacks";
  passed: boolean;
  exit_code?: number | null;
  detail?: string;
};

export type ExperimentsTrialRecordV1 = {
  schema_version: "1.0.0";
  experiment_id: string;
  experiment_digest: ExperimentsTrialRecordV1DefsDigest;
  suite_digest: ExperimentsTrialRecordV1DefsDigest;
  trial_id: string;
  arm_id: string;
  task_id: string;
  repetition: number;
  sequence: number;
  status: "completed" | "launch-failed" | "collect-failed" | "skipped";
  run: {
    run_id?: string;
    status?: string;
    workspace_root?: string;
    report_path?: string;
    workflow_digest?: ExperimentsTrialRecordV1DefsDigest;
    policy_digest?: ExperimentsTrialRecordV1DefsDigest;
    execution_profile_digest?: ExperimentsTrialRecordV1DefsDigest;
    context_mode?: "legacy" | "bounded";
    provider?: string;
    model?: string | null;
    reasoning_effort?: string | null;
    runtime_identity?: { [key: string]: unknown } | null;
    started_at: ExperimentsTrialRecordV1DefsTimestamp;
    finished_at: ExperimentsTrialRecordV1DefsTimestamp;
    wall_clock_ms: number;
  };
  outcome: {
    pass: boolean | null;
    reached_ship_state: boolean;
    acceptance_pass: boolean | null;
    acceptance: Array<ExperimentsTrialRecordV1DefsCheckResult>;
    seeded_defects_shipped: number | null;
    seeded_defects: Array<ExperimentsTrialRecordV1DefsCheckResult>;
  };
  measurements: {
    provider_attempts: number;
    nodes: { passed: number; failed: number; blocked: number; stopped: number; skipped: number };
    repair_rounds: number;
    changed_paths: number;
    tokens: {
      measurement_status: "complete" | "partial" | "unavailable";
      attempts_measured: number;
      input_tokens?: number;
      cached_input_tokens?: number;
      output_tokens?: number;
      reasoning_output_tokens?: number;
    };
    estimated_cost: { currency: string; value: number; basis: "arm-pricing" } | null;
  };
  failure_layer_labels: Array<{
    rater: string;
    layer: "representation" | "inference" | "coordination" | "governance" | "none";
    note?: string;
    labeled_at: ExperimentsTrialRecordV1DefsTimestamp;
  }>;
  evidence_refs: Array<string>;
  error?: string;
};

export type GraphGraphContext = {
  schema_version: "1.0.0";
  repository_id: string;
  snapshot_id: string;
  run_id: string | null;
  phase: string;
  query_id: string;
  seed: string;
  generated_at: string;
  limits: { max_depth: number; max_records: number };
  records: Array<{
    node_id: string;
    kind: string;
    selection_reason: string;
    traversal_path: Array<string>;
    trust_class: string;
    source_ref: string;
    source_digest: string;
    staleness: "current" | "historical" | "stale" | "conflicting";
    score: { exact: number; lexical: number; distance: number; total: number };
    snippet: string;
  }>;
};

export type GraphGraphEdge = {
  record_type: "edge";
  graph_family: "evidence" | "workflow" | "repository" | "memory";
  repository_id: string;
  run_id: string | null;
  kind:
    | "CONTAINS"
    | "DEPENDS_ON"
    | "REFERENCES"
    | "READS"
    | "WRITES"
    | "DERIVED_FROM"
    | "COVERS"
    | "VERIFIES"
    | "EVALUATES"
    | "AUTHORIZED_BY"
    | "SUPPORTS_CLAIM"
    | "SUPERSEDES"
    | "INVALIDATES"
    | "INSTANCE_OF"
    | "NEXT"
    | "SELECTS"
    | "RECOMMENDS";
  logical_id: string;
  version_id: string;
  from: string;
  to: string;
  source_ref: string;
  source_digest: string;
  projector: string;
  transaction_time: string;
  valid_from?: string | null;
  valid_to?: string | null;
  trust_class: "authoritative" | "verified-derived" | "model-proposed" | "untrusted";
  attributes: { [key: string]: unknown };
};

export type GraphGraphManifest = {
  schema_version: "1.0.0";
  projector: string;
  repository_id: string;
  snapshot_id: string;
  run_id: string | null;
  transaction_time: string;
  node_count: number;
  edge_count: number;
  nodes_digest: string;
  edges_digest: string;
  canonical_digest: string;
  limits: { max_nodes: 250000; max_edges: 1000000; max_file_bytes: 1048576 };
  validation: { valid: boolean; issues: Array<string> };
};

export type GraphGraphNode = {
  record_type: "node";
  graph_family: "evidence" | "workflow" | "repository" | "memory";
  repository_id: string;
  run_id: string | null;
  kind:
    | "Repository"
    | "ProjectSnapshot"
    | "Run"
    | "PhaseAttempt"
    | "WorkflowRevision"
    | "AgentNode"
    | "NodeAttempt"
    | "Join"
    | "LoopIteration"
    | "Candidate"
    | "Evaluation"
    | "Recommendation"
    | "ActivationDecision"
    | "Requirement"
    | "Constraint"
    | "PlanTask"
    | "TestCase"
    | "File"
    | "ArtifactVersion"
    | "CommandExecution"
    | "GateDecision"
    | "CheckpointDecision"
    | "Finding"
    | "Claim"
    | "SourceDocument";
  logical_id: string;
  version_id: string;
  source_ref: string;
  source_digest: string;
  projector: string;
  transaction_time: string;
  valid_from?: string | null;
  valid_to?: string | null;
  trust_class: "authoritative" | "verified-derived" | "model-proposed" | "untrusted";
  attributes: { [key: string]: unknown };
};

export type GraphMemoryDecision = {
  schema_version: "1.0.0";
  decision_id: string;
  candidate_id: string;
  decision: "promoted" | "rejected" | "superseded" | "invalidated";
  actor: string;
  rationale: string;
  source_ref: string;
  source_digest: string;
  recorded_at: string;
};

export type Permissions = {
  network?: { allow?: Array<string> };
  filesystem?: { read?: Array<string>; write?: Array<string> };
  process?: { allow_subprocess?: boolean };
  limits?: { max_files?: number; max_file_mb?: number };
};

export type QualityGate = {
  gate_id: string;
  phase:
    | "arm"
    | "design"
    | "adversarial-review"
    | "plan"
    | "pmatch"
    | "build"
    | "quality-static"
    | "quality-tests"
    | "post-build"
    | "denoise"
    | "quality-frontend"
    | "quality-backend"
    | "quality-docs"
    | "security-review"
    | "release-readiness";
  status: "pass" | "fail" | "warn";
  criteria: Array<{ name: string; passed: boolean; evidence: string }>;
  blocking_failures: Array<string>;
  artifact_ref: string;
  schema_validation: { valid: boolean; errors: Array<string> };
  timestamp: string;
};

export type RunResult = {
  success: boolean;
  data?: { [key: string]: unknown };
  error?: { code: string; message: string; details?: JsonValue; [key: string]: unknown };
  metadata: { tool_version: string; execution_time_ms: number; [key: string]: unknown };
  logs: Array<string>;
};

export type SkillManifest = {
  id: string;
  name: string;
  version: string;
  description: string;
  category: string;
  language: string;
  entrypoint: { command: Array<string> };
  schemas: { input: string; output: string };
  sandbox: { dockerfile: string; permissions: string };
  capabilities: Array<string>;
  limits: { timeout_ms: number; max_output_kb: number };
};

export type ToolDefinition = {
  name: string;
  description: string;
  parameters: { [key: string]: unknown };
};

export type WorkflowsExecutionProfileV1DefsMapping = {
  model: string;
  reasoning_effort: "low" | "medium" | "high" | "xhigh";
};

export type WorkflowsExecutionProfileV1 = {
  schema_version: "1.0.0";
  profile_id: string;
  tiers: {
    economy: WorkflowsExecutionProfileV1DefsMapping;
    standard: WorkflowsExecutionProfileV1DefsMapping;
    judgment: WorkflowsExecutionProfileV1DefsMapping;
  };
};

export type WorkflowsExecutionProfileV2DefsModelMapping = {
  model: string;
  reasoning_effort: "low" | "medium" | "high" | "xhigh";
};

export type WorkflowsExecutionProfileV2DefsName = string;

export type WorkflowsExecutionProfileV2 = {
  schema_version: "2.0.0";
  profile_id: string;
  tiers: {
    economy: WorkflowsExecutionProfileV2DefsModelMapping;
    standard: WorkflowsExecutionProfileV2DefsModelMapping;
    judgment: WorkflowsExecutionProfileV2DefsModelMapping;
  };
  capability_sets: { [key: string]: unknown };
  default_capability_set: WorkflowsExecutionProfileV2DefsName;
  node_capability_sets: { [key: string]: unknown };
};

export type WorkflowsExecutionProfileV3DefsRouteId = string;

export type WorkflowsExecutionProfileV3 = {
  schema_version: "3.0.0";
  profile_id: string;
  routes: { [key: string]: unknown };
  tiers: {
    economy: WorkflowsExecutionProfileV3DefsRouteId;
    standard: WorkflowsExecutionProfileV3DefsRouteId;
    judgment: WorkflowsExecutionProfileV3DefsRouteId;
  };
  node_routes?: { [key: string]: unknown };
};

export type WorkflowsNodeEnvelopeV21 = {
  schema_version: "2.1.0";
  run_id: string;
  workflow_digest: string;
  node_id: string;
  instance_id: string;
  parent_node?: string | null;
  item_key?: string | null;
  item_digest?: string | null;
  attempt: number;
  loop_iteration?: number;
  status: "passed" | "failed" | "blocked" | "stopped" | "skipped" | "collected";
  failure?: { [key: string]: unknown } | null;
  payload: JsonValue;
  findings: Array<{ [key: string]: unknown }>;
  evidence_refs: Array<string>;
  ownership: { [key: string]: unknown };
  changed_paths: Array<string>;
  command_evidence: Array<{ [key: string]: unknown }>;
  resource_usage: { [key: string]: unknown };
  input_digest: string;
  output_digest: string;
  execution_tier: "economy" | "standard" | "judgment" | "runtime";
  selection?: { [key: string]: unknown } | null;
  quorum?: { [key: string]: unknown } | null;
  convergence?: { [key: string]: unknown } | null;
};

export type WorkflowsNodeEnvelopeV22 = {
  schema_version: "2.2.0";
  run_id: string;
  workflow_digest: string;
  node_id: string;
  instance_id: string;
  attempt: number;
  status: "passed" | "failed" | "blocked" | "stopped" | "skipped";
  failure?: { [key: string]: unknown } | null;
  payload: JsonValue;
  findings: Array<{ [key: string]: unknown }>;
  evidence_refs: Array<string>;
  ownership: { [key: string]: unknown };
  changed_paths: Array<string>;
  command_evidence: Array<{ [key: string]: unknown }>;
  resource_usage: { [key: string]: unknown };
  input_digest: string;
  output_digest: string;
  execution_tier: "economy" | "standard" | "judgment" | "runtime";
  context_manifest: {
    cap_bytes: number;
    assembled_bytes: number;
    mandatory_budget_bytes: number;
    optional_budget_bytes: number;
    included: Array<{ [key: string]: unknown }>;
    omitted: Array<{ [key: string]: unknown }>;
    artifact_refs: Array<{ [key: string]: unknown }>;
    inline_artifacts: Array<{ [key: string]: unknown }>;
  };
};

export type WorkflowsNodeEnvelopeV2 = {
  schema_version: "2.0.0";
  run_id: string;
  workflow_digest: string;
  node_id: string;
  attempt: number;
  loop_iteration?: number;
  status: "passed" | "failed" | "blocked" | "stopped" | "skipped";
  payload: JsonValue;
  findings: Array<{ [key: string]: unknown }>;
  evidence_refs: Array<string>;
  ownership: { [key: string]: unknown };
  changed_paths: Array<string>;
  command_evidence: Array<{ [key: string]: unknown }>;
  resource_usage: { [key: string]: unknown };
  input_digest: string;
  output_digest: string;
};

export type WorkflowsWorkflowV21DefsNodeId = string;

export type WorkflowsWorkflowV21DefsQuorum = {
  threshold: number;
  groups?: Array<{ id: string; members: Array<WorkflowsWorkflowV21DefsNodeId>; threshold: number }>;
};

export type WorkflowsWorkflowV21DefsPointer = string;

export type WorkflowsWorkflowV21DefsMap = {
  source_pointer: WorkflowsWorkflowV21DefsPointer;
  stable_key_pointer: WorkflowsWorkflowV21DefsPointer;
  max_items?: number;
};

export type WorkflowsWorkflowV21DefsTransform = {
  operation: "select" | "flatten" | "deduplicate" | "sort" | "limit" | "group" | "cartesian";
  source_pointer?: WorkflowsWorkflowV21DefsPointer;
  value_pointer?: WorkflowsWorkflowV21DefsPointer;
  key_pointer?: WorkflowsWorkflowV21DefsPointer;
  pointers?: Array<WorkflowsWorkflowV21DefsPointer>;
  limit?: number;
  descending?: boolean;
};

export type WorkflowsWorkflowV21DefsFailure = {
  mode: "fail-workflow" | "collect";
  max_failures?: number;
  minimum_successes?: number;
};

export type WorkflowsWorkflowV21DefsLoop = {
  mode?: "bounded" | "until-dry";
  max_iterations: number;
  members: Array<WorkflowsWorkflowV21DefsNodeId>;
  source_pointer?: WorkflowsWorkflowV21DefsPointer;
  stable_key_pointer?: WorkflowsWorkflowV21DefsPointer;
};

export type WorkflowsWorkflowV21DefsNode = {
  id: WorkflowsWorkflowV21DefsNodeId;
  kind: "agent" | "map" | "transform" | "join" | "gate" | "checkpoint" | "loop" | "terminal";
  access: "read" | "write" | "control";
  guidance: string;
  role?: string;
  payload_contract?: string;
  tier?: "economy" | "standard" | "judgment";
  join?: "all" | "any" | "quorum";
  quorum?: WorkflowsWorkflowV21DefsQuorum;
  map?: WorkflowsWorkflowV21DefsMap;
  transform?: WorkflowsWorkflowV21DefsTransform;
  failure_handling?: WorkflowsWorkflowV21DefsFailure;
  resource?: string;
  ownership_plan?: boolean;
  mutation_checkpoint?: boolean;
  verification?: boolean;
  loop?: WorkflowsWorkflowV21DefsLoop;
};

export type WorkflowsWorkflowV21DefsEdge = {
  from: WorkflowsWorkflowV21DefsNodeId;
  to: WorkflowsWorkflowV21DefsNodeId;
  type: "sequence" | "artifact" | "stream" | "condition" | "loop-back";
  artifact?: string;
  condition?: "success" | "failure" | "blocking-findings" | "budget-available";
};

export type WorkflowsWorkflowV21 = {
  schema_version: "2.1.0";
  workflow_id: string;
  revision: number;
  title?: string;
  entry_node: WorkflowsWorkflowV21DefsNodeId;
  terminal_node: WorkflowsWorkflowV21DefsNodeId;
  nodes: Array<WorkflowsWorkflowV21DefsNode>;
  edges: Array<WorkflowsWorkflowV21DefsEdge>;
  payload_contracts?: { [key: string]: unknown };
  budgets?: {
    max_concurrency?: number;
    max_repair_rounds?: number;
    max_attempts_per_node?: number;
    max_dynamic_instances?: number;
    max_pipeline_depth?: number;
    max_map_items?: number;
    max_wall_clock_seconds?: number;
    max_provider_attempts?: number;
  };
};

export type WorkflowsWorkflowV22DefsNodeId = string;

export type WorkflowsWorkflowV22DefsSignalName = string;

export type WorkflowsWorkflowV22DefsWait = {
  timeout_seconds: number;
  signals: Array<WorkflowsWorkflowV22DefsSignalName>;
  signal_contract: string;
};

export type WorkflowsWorkflowV22DefsNode = {
  id: WorkflowsWorkflowV22DefsNodeId;
  kind: "agent" | "join" | "gate" | "checkpoint" | "wait" | "terminal";
  access: "read" | "write" | "control";
  guidance: string;
  role?: string;
  payload_contract?: string;
  tier?: "economy" | "standard" | "judgment";
  join?: "all" | "any";
  resource?: string;
  ownership_plan?: boolean;
  mutation_checkpoint?: boolean;
  verification?: boolean;
  context?: { include_operational_evidence?: boolean };
  wait?: WorkflowsWorkflowV22DefsWait;
};

export type WorkflowsWorkflowV22DefsEdge = {
  from: WorkflowsWorkflowV22DefsNodeId;
  to: WorkflowsWorkflowV22DefsNodeId;
  type: "sequence" | "artifact" | "condition";
  artifact?: string;
  condition?: "success" | "failure" | "blocking-findings" | "budget-available";
};

export type WorkflowsWorkflowV22 = {
  schema_version: "2.2.0";
  workflow_id: string;
  revision: number;
  title?: string;
  entry_node: WorkflowsWorkflowV22DefsNodeId;
  terminal_node: WorkflowsWorkflowV22DefsNodeId;
  nodes: Array<WorkflowsWorkflowV22DefsNode>;
  edges: Array<WorkflowsWorkflowV22DefsEdge>;
  payload_contracts?: { [key: string]: unknown };
  signal_contracts: { [key: string]: unknown };
  budgets?: {
    max_concurrency?: number;
    max_attempts_per_node?: number;
    max_context_bytes?: number;
  };
};

export type WorkflowsWorkflowV2DefsNodeId = string;

export type WorkflowsWorkflowV2DefsNode = {
  id: WorkflowsWorkflowV2DefsNodeId;
  kind: "agent" | "join" | "gate" | "checkpoint" | "loop" | "terminal";
  access: "read" | "write" | "control";
  guidance: string;
  role?: string;
  payload_contract?: string;
  join?: "all" | "any";
  resource?: string;
  ownership_plan?: boolean;
  mutation_checkpoint?: boolean;
  verification?: boolean;
  loop?: { max_iterations: number; members: Array<WorkflowsWorkflowV2DefsNodeId> };
};

export type WorkflowsWorkflowV2DefsEdge = {
  from: WorkflowsWorkflowV2DefsNodeId;
  to: WorkflowsWorkflowV2DefsNodeId;
  type: "sequence" | "artifact" | "condition" | "loop-back";
  artifact?: string;
  condition?: "success" | "failure" | "blocking-findings" | "budget-available";
};

export type WorkflowsWorkflowV2 = {
  schema_version: "2.0.0";
  workflow_id: string;
  revision: number;
  title?: string;
  entry_node: WorkflowsWorkflowV2DefsNodeId;
  terminal_node: WorkflowsWorkflowV2DefsNodeId;
  nodes: Array<WorkflowsWorkflowV2DefsNode>;
  edges: Array<WorkflowsWorkflowV2DefsEdge>;
  payload_contracts?: { [key: string]: unknown };
  budgets?: {
    max_concurrency?: number;
    max_repair_rounds?: number;
    max_attempts_per_node?: number;
    max_wall_clock_seconds?: number;
    max_provider_attempts?: number;
  };
};

export interface ContractTypes {
  "artifacts/brief.schema.json": ArtifactsBrief;
  "artifacts/build-report.schema.json": ArtifactsBuildReport;
  "artifacts/context-manifest-gate.schema.json": ArtifactsContextManifestGate;
  "artifacts/design-document.schema.json": ArtifactsDesignDocument;
  "artifacts/drift-report.schema.json": ArtifactsDriftReport;
  "artifacts/execution-plan.schema.json": ArtifactsExecutionPlan;
  "artifacts/execution-trace.schema.json": ArtifactsExecutionTrace;
  "artifacts/operator-checkpoint.schema.json": ArtifactsOperatorCheckpoint;
  "artifacts/operator-control.schema.json": ArtifactsOperatorControl;
  "artifacts/progress-summary.schema.json": ArtifactsProgressSummary;
  "artifacts/quality-report.schema.json": ArtifactsQualityReport;
  "artifacts/release-readiness.schema.json": ArtifactsReleaseReadiness;
  "artifacts/review-loop.schema.json": ArtifactsReviewLoop;
  "artifacts/review-report.schema.json": ArtifactsReviewReport;
  "artifacts/traceability-check.schema.json": ArtifactsTraceabilityCheck;
  "autonomous-policy.schema.json": AutonomousPolicy;
  "experiments/evidence-manifest-v1.schema.json": ExperimentsEvidenceManifestV1;
  "experiments/experiment-report-v1.schema.json": ExperimentsExperimentReportV1;
  "experiments/experiment-report-v2.schema.json": ExperimentsExperimentReportV2;
  "experiments/experiment-v1.schema.json": ExperimentsExperimentV1;
  "experiments/task-suite-v1.schema.json": ExperimentsTaskSuiteV1;
  "experiments/trial-execution-v1.schema.json": ExperimentsTrialExecutionV1;
  "experiments/trial-record-v1.schema.json": ExperimentsTrialRecordV1;
  "graph/graph-context.schema.json": GraphGraphContext;
  "graph/graph-edge.schema.json": GraphGraphEdge;
  "graph/graph-manifest.schema.json": GraphGraphManifest;
  "graph/graph-node.schema.json": GraphGraphNode;
  "graph/memory-decision.schema.json": GraphMemoryDecision;
  "permissions.schema.json": Permissions;
  "quality-gate.schema.json": QualityGate;
  "run-result.schema.json": RunResult;
  "skill-manifest.schema.json": SkillManifest;
  "tool-definition.schema.json": ToolDefinition;
  "workflows/execution-profile-v1.schema.json": WorkflowsExecutionProfileV1;
  "workflows/execution-profile-v2.schema.json": WorkflowsExecutionProfileV2;
  "workflows/execution-profile-v3.schema.json": WorkflowsExecutionProfileV3;
  "workflows/node-envelope-v2.1.schema.json": WorkflowsNodeEnvelopeV21;
  "workflows/node-envelope-v2.2.schema.json": WorkflowsNodeEnvelopeV22;
  "workflows/node-envelope-v2.schema.json": WorkflowsNodeEnvelopeV2;
  "workflows/workflow-v2.1.schema.json": WorkflowsWorkflowV21;
  "workflows/workflow-v2.2.schema.json": WorkflowsWorkflowV22;
  "workflows/workflow-v2.schema.json": WorkflowsWorkflowV2;
}
export const schemaDigests = {
  "artifacts/brief.schema.json": "020b1e40e0951da1eb288940ed6b7e032aa118947b75961cf8c62c08f6459c56",
  "artifacts/build-report.schema.json":
    "b8ec043a6690f7092291872440bc35a739d5af39af22c3faf44ec254ab3f021c",
  "artifacts/context-manifest-gate.schema.json":
    "ccfac8d8a4d5a1f7e0cf8994830e8171429b48845db3e5c4405505b5666ad4d3",
  "artifacts/design-document.schema.json":
    "05a0532239c6e5a432ed1d087b33b69319e2751ab073b0f2e5ca4825b6cf576d",
  "artifacts/drift-report.schema.json":
    "bad9e42e98c5c6fc208e6dc7d6af40e79da65ed79dde66ca398f02d7f7489d65",
  "artifacts/execution-plan.schema.json":
    "d022d481461ac15c5d4adf78daa26ba86418b66369eac83ae70b72365a392e88",
  "artifacts/execution-trace.schema.json":
    "4c45bd8777d28922a6da6c18638ca7bd8a0889de4e0a2cd1f5ad264f03e9722a",
  "artifacts/operator-checkpoint.schema.json":
    "8b827baf5e7b1ee6a5f7f1e309494d9d1e3e3931eb1af2f3472d4d2d76e40dd2",
  "artifacts/operator-control.schema.json":
    "b9c21c3f20cebc34ecc8a4dd201a76bab0577ba8f8b3874569d247ed9eb0dc72",
  "artifacts/progress-summary.schema.json":
    "cc315946f2db064ff7adf6a974a3b1dd6281bb979a57526bc02fcd0b54015cbc",
  "artifacts/quality-report.schema.json":
    "59bb35f0830bfa127ac0955a1bb27e728584a5e994cbf0a30d585a07b50d4895",
  "artifacts/release-readiness.schema.json":
    "ef38c2252a62778a450d48732b7c63d631602122ab32066388d203bb73b4ccba",
  "artifacts/review-loop.schema.json":
    "9fae9020b1a52827cce69584cdba789ea0d4502dd8780fde647f7c10c4300c25",
  "artifacts/review-report.schema.json":
    "d014cc9cc95bda40149895993e55bbad3b241aa57938500f707c99bdc986e0a2",
  "artifacts/traceability-check.schema.json":
    "d9b30cc2ca26ad046ccbbec683c3684cb2e447f7bc5364b26377cfbddf76c2c1",
  "autonomous-policy.schema.json":
    "2fd824dc499a994f34c13654b49c1b0770f1d94918151d59657848903040fad9",
  "experiments/evidence-manifest-v1.schema.json":
    "599f191f8c8415de2f2b58be90a0c23d1fb780aa671decdf2dded845247e8d54",
  "experiments/experiment-report-v1.schema.json":
    "37a5084efbe6981ec78aec04ea8fcba62de11dee9f5f07200f7138d9a73e5f72",
  "experiments/experiment-report-v2.schema.json":
    "70616174032a691ce476e89d5b3719591f4648641b36e1c8090bf59a44bc099c",
  "experiments/experiment-v1.schema.json":
    "97f3d5fda9e322786152eb0bc9384739fbcb7aa764fc9dbbf77b8b3871d71d44",
  "experiments/task-suite-v1.schema.json":
    "46f800601434edb35058d26028ea94bcb93518e911608207b2736337f0aafab6",
  "experiments/trial-execution-v1.schema.json":
    "ca352896c9ae17c163d7eee4add6c8ba34f6e4a05af934675319a24491f5c8bd",
  "experiments/trial-record-v1.schema.json":
    "e165de67e32840aa14375ed87d76f5e4236a20e125be2304ac6f2fdc75f8afc8",
  "graph/graph-context.schema.json":
    "d91bbeacc4d7dec22fb2e0d2ab1570c7beba19f8316dbb9839e94f29edb69b05",
  "graph/graph-edge.schema.json":
    "843d6ec1f90112441f56e48a90322ab51625ed0d46487f2ccfa1bab6355b1a2d",
  "graph/graph-manifest.schema.json":
    "ae011f6e41c4ba7908c879da72ce98ee8ac5f8876997f4df0e9506eeaffe6b10",
  "graph/graph-node.schema.json":
    "715ff9853a3c7f8b39b941ef5ef225b704000d0fbfba4489d4cc1eba37d8b07d",
  "graph/memory-decision.schema.json":
    "36b8156e649ff105a6b214eb8235635a659c0a4d1234610a4427724619ccbfe0",
  "permissions.schema.json": "68950bbdb64273eb4c5c85bf964d0b8b389ef82e1ab5ee572c9e1212da20ed2e",
  "quality-gate.schema.json": "61b97fdcbeaa334d6eb2eec1c7646df478eba5a8a6cf69f8eae5afca6770e4eb",
  "run-result.schema.json": "ae4ea58b6ebb7a9cb7e63c8ef35f55a5f7d1b8abd2e5af2a1fabbc12cdbfa716",
  "skill-manifest.schema.json": "aa26cd8b70a67f60c12168f4802a7889758b21e88aa8b81ce21fad721db37d6b",
  "tool-definition.schema.json": "0f1597377160ebbd0fcef17fec36bfd7da8b89f01e47f6fe6812640fca5cab1f",
  "workflows/execution-profile-v1.schema.json":
    "d9fa7fb87a887770b2d0c68491eb7e3aafeba2698e154d678b9d556aab102f39",
  "workflows/execution-profile-v2.schema.json":
    "21a01944001d485af109ab48f3a953868447a0d6d64550295d0adcad93b665e9",
  "workflows/execution-profile-v3.schema.json":
    "e77bec19262ce93977a2f53cd38475d695effbc5ae1855f1ef8db3687ab727d2",
  "workflows/node-envelope-v2.1.schema.json":
    "a23b84e5de5f332164f4876aacf815f7a15338f2cb9565a821abda3c539a29a3",
  "workflows/node-envelope-v2.2.schema.json":
    "56292f2e461fb08099e1f7bdca78406df5a95e80f85e535905b10a510b08f420",
  "workflows/node-envelope-v2.schema.json":
    "97bb56a3ec5ab98e2fe2208cf2df8ed2342ca83942d3b97b5f96fd85b64a7315",
  "workflows/workflow-v2.1.schema.json":
    "82ecd3d1dfd00a034bd9aa2039a4f99591f0089dbc33fef5cfffb8d3946035cf",
  "workflows/workflow-v2.2.schema.json":
    "8923e5350ed75117a0db86b024c4dfd4400dfd1ddf8b70f9e5abf052cd2dc643",
  "workflows/workflow-v2.schema.json":
    "df55459b61b4ebdae3a6240a3a990268f541ccdfe7a04b0eb32be764aba9b725",
} as const;
