/** Shared operator console state and element registry. */
import type { OperatorElement, OperatorRun, OperatorState } from "./types.js";

export const state: OperatorState = {
  token: new URLSearchParams(location.hash.slice(1)).get("token"),
  projects: [],
  projectId: null,
  runs: [],
  runsCursor: null,
  runsHasMore: false,
  runsLoadingMore: false,
  runId: null,
  runDetail: null,
  detailGeneration: 0,
  detailLoading: false,
  detailError: null,
  events: [],
  eventIds: new Set(),
  eventAfter: 0,
  eventFrame: null,
  eventError: null,
  runQuery: "",
  runFilter: "all",
  confirmAction: null,
  actionPending: false,
  runsGeneration: 0,
  streamAbort: null,
  streamGeneration: 0,
  workflows: [],
  workflowId: null,
  workflow: null,
  workflowView: "graph",
  workflowProfiles: [],
  workflowNodeId: null,
  workflowEdgeKey: null,
};

export const elements = Object.fromEntries(
  [
    "project-select",
    "connection-status",
    "decisions-pending",
    "decisions-pending-count",
    "decisions-pending-label",
    "search-shortcut",
    "new-run-button",
    "toggle-search",
    "cycle-filter",
    "filter-label",
    "run-search",
    "run-search-input",
    "runs-loading",
    "runs-list",
    "runs-load-more",
    "runs-empty",
    "workspace-empty",
    "run-content",
    "run-task",
    "task-toggle",
    "run-title",
    "run-branch",
    "run-workspace",
    "run-terminal",
    "phase-list",
    "gate-count",
    "artifact-count",
    "agent-count",
    "input-count",
    "output-count",
    "cost-count",
    "updated-value",
    "event-list",
    "event-count",
    "stream-status",
    "expand-all",
    "collapse-all",
    "checkpoint-empty",
    "checkpoint-empty-copy",
    "checkpoint-content",
    "checkpoint-title",
    "checkpoint-message",
    "checkpoint-rationale",
    "rationale-count",
    "decision-error",
    "decision-form",
    "decision-panel",
    "checkpoint-meta",
    "context-started",
    "next-step-copy",
    "review-jump",
    "stop-button",
    "interrupt-button",
    "resume-button",
    "cleanup-button",
    "toast",
    "error-toast",
    "error-toast-message",
    "error-toast-close",
    "start-dialog",
    "start-form",
    "start-task",
    "start-checkpoint-policy",
    "start-execution-profile",
    "workflow-proposal-profile",
    "start-submit",
    "start-pending",
    "start-close",
    "start-cancel",
    "confirm-dialog",
    "confirm-form",
    "confirm-kicker",
    "confirm-heading",
    "confirm-message",
    "confirm-rationale",
    "confirm-run-id-field",
    "confirm-help",
    "confirm-error",
    "confirm-pending",
    "confirm-expected-id",
    "confirm-run-id",
    "confirm-submit",
    "confirm-close",
    "confirm-cancel",
    "workflow-refresh",
    "workflow-list",
    "workflow-empty",
    "workflow-graph",
    "workflow-graph-content",
    "workflow-view-loop",
    "workflow-view-graph",
    "workflow-view-analyze",
    "workflow-view-json",
    "workflow-loop",
    "workflow-loop-summary",
    "workflow-graph-panel",
    "workflow-analysis",
    "workflow-analysis-output",
    "workflow-json",
    "workflow-template",
    "workflow-version-help",
    "workflow-structured-controls",
    "workflow-definition",
    "workflow-actor",
    "workflow-rationale",
    "workflow-budget",
    "workflow-structure",
    "workflow-draft-form",
    "workflow-draft",
    "workflow-validate",
    "workflow-add-node",
    "workflow-delete-node",
    "workflow-add-edge",
    "workflow-delete-edge",
    "workflow-proposal-task",
    "workflow-propose",
    "workflow-node-select",
    "workflow-edge-select",
    "workflow-inspector-help",
    "workflow-node-guidance",
    "workflow-node-role",
    "workflow-node-kind",
    "workflow-node-access",
    "workflow-node-tier",
    "workflow-node-payload",
    "workflow-node-join",
    "workflow-node-quorum",
    "workflow-node-failure",
    "workflow-node-resource",
    "workflow-node-verification",
    "workflow-node-checkpoint",
    "workflow-node-checkpoint-field",
    "workflow-node-ownership",
    "workflow-node-loop-mode",
    "workflow-node-loop-bound",
    "workflow-node-loop-members",
    "workflow-details",
    "workflow-diff-base",
    "workflow-diff",
    "workflow-diff-output",
    "workflow-activate",
    "workflow-digest-confirmation",
    "workflow-history",
    "workflow-status",
  ].map((id) => [id, document.getElementById(id) as OperatorElement]),
) as Record<string, OperatorElement>;

if (state.token) history.replaceState(null, "", `${location.pathname}${location.search}`);

export function currentRun(): OperatorRun | null {
  if (state.runDetail?.id === state.runId) return state.runDetail;
  return state.runs.find((run) => run.id === state.runId && run.gates) ?? null;
}

/** The selected catalogue row, which exists before (or without) the run detail. */
export function selectedSummary(): OperatorRun | null {
  return state.runs.find((run) => run.id === state.runId) ?? null;
}
